# Site settings
title: ASD
url: "http://asduser.github.io"    # the protocol and hostname of your site
baseurl: ""
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
# email: your_email@example.com
author: Another Software Developer
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "http://asduser.github.io/images/blog_logo_sidebar.png"
profile: "In theory, theory and practice are the same. In practice, they’re not."
#twitter_username: twitter_username
github_username:  asduser

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

  # syntax_highlighter_opts:    
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
  #     start_line: 1

favicon: "/images/3066.png"